forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
mod "puppetlabs/apache"
mod "puppetlabs/ntp"
mod "puppetlabs/stdlib"
mod "puppetlabs/ruby"
mod "puppetlabs/gcc"
mod "puppetlabs/pe_gem"
mod "croddy/make"
mod "puppetlabs/inifile"
mod "puppetlabs/vcsrepo"
mod "puppetlabs/git"
mod "puppetlabs/concat"
mod "gentoo/portage"
mod "zack/r10k"
mod "nanliu/staging"
mod "puppetlabs/splunk"
mod "puppetlabs/apt"
mod "puppetlabs/java"
mod "darin/zypprepo"
mod "rtyler/jenkins"
mod "puppetlabs/nginx"
